export type TeamMeta = { abbr: string; conference: "AFC" | "NFC"; division: "East" | "North" | "South" | "West" };
export const TEAM_META: TeamMeta[] = [
  { abbr: "BUF", conference: "AFC", division: "East" },
  { abbr: "MIA", conference: "AFC", division: "East" },
  { abbr: "NYJ", conference: "AFC", division: "East" },
  { abbr: "NE",  conference: "AFC", division: "East" },
  { abbr: "BAL", conference: "AFC", division: "North" },
  { abbr: "CIN", conference: "AFC", division: "North" },
  { abbr: "CLE", conference: "AFC", division: "North" },
  { abbr: "PIT", conference: "AFC", division: "North" },
  { abbr: "HOU", conference: "AFC", division: "South" },
  { abbr: "IND", conference: "AFC", division: "South" },
  { abbr: "JAX", conference: "AFC", division: "South" },
  { abbr: "TEN", conference: "AFC", division: "South" },
  { abbr: "DEN", conference: "AFC", division: "West" },
  { abbr: "KC",  conference: "AFC", division: "West" },
  { abbr: "LV",  conference: "AFC", division: "West" },
  { abbr: "LAC", conference: "AFC", division: "West" },
  { abbr: "DAL", conference: "NFC", division: "East" },
  { abbr: "NYG", conference: "NFC", division: "East" },
  { abbr: "PHI", conference: "NFC", division: "East" },
  { abbr: "WSH", conference: "NFC", division: "East" },
  { abbr: "CHI", conference: "NFC", division: "North" },
  { abbr: "DET", conference: "NFC", division: "North" },
  { abbr: "GB",  conference: "NFC", division: "North" },
  { abbr: "MIN", conference: "NFC", division: "North" },
  { abbr: "ATL", conference: "NFC", division: "South" },
  { abbr: "CAR", conference: "NFC", division: "South" },
  { abbr: "NO",  conference: "NFC", division: "South" },
  { abbr: "TB",  conference: "NFC", division: "South" },
  { abbr: "ARI", conference: "NFC", division: "West" },
  { abbr: "LAR", conference: "NFC", division: "West" },
  { abbr: "SF",  conference: "NFC", division: "West" },
  { abbr: "SEA", conference: "NFC", division: "West" }
];
export const META_BY_ABBR = Object.fromEntries(TEAM_META.map(t => [t.abbr, t]));
